- name: Upgrade all packages (Debian/Ubuntu)
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
  when: ansible_facts["os_family"] == "Debian"

- name: Upgrade all packages (RHEL/CentOS)
  ansible.builtin.dnf:
    name: "*"
    state: latest
  when: ansible_facts["os_family"] == "RedHat"

- name: Modify /etc/hosts if local setup
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^\s*127\.0\.0\.1\s+backend(\s|$)'
    line: '127.0.0.1    backend'
    state: present
  when: local | default(false) | bool
